package factura.entities;
// Generated 13-dic-2013 0:40:01 by Hibernate Tools 3.2.1.GA

import ec.ste.factura.DatabaseEntity;

import javax.persistence.*;
import java.util.Date;

/**
 * Retencion generated by hbm2java
 */
@Entity
@Table(name = "retencion", schema = "public")
public class Retencion extends DatabaseEntity implements java.io.Serializable {

    private int retCodigo;
    private Empresa empresa;
    private Tipo tipo;
    private String retNumAutorizacion;
    private String retFechaAutorizacion;
    private String retIdentificacionEmisor;
    private String retRazonSocialEmisor;
    private String retEstablecimiento;
    private String retPuntoEmision;
    private int retSecuencial;
    private Date retFechaEmision;
    private String retIdentificacionRetenido;
    private String retRazonSocialRetenido;
    private double retValorRetenido;

    public Retencion() {
    }

   

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ret_codigo", unique = true, nullable = false)
    public int getRetCodigo() {
        return this.retCodigo;
    }

    public void setRetCodigo(int retCodigo) {
        this.retCodigo = retCodigo;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "emp_codigo")
    public Empresa getEmpresa() {
        return this.empresa;
    }

    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "tip_codigo")
    public Tipo getTipo() {
        return this.tipo;
    }

    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }

    @Column(name = "ret_num_autorizacion", nullable = false, length = 100)
    public String getRetNumAutorizacion() {
        return this.retNumAutorizacion;
    }

    public void setRetNumAutorizacion(String retNumAutorizacion) {
        this.retNumAutorizacion = retNumAutorizacion;
    }

    @Column(name = "ret_fecha_autorizacion", nullable = false, length = 50)
    public String getRetFechaAutorizacion() {
        return this.retFechaAutorizacion;
    }

    public void setRetFechaAutorizacion(String retFechaAutorizacion) {
        this.retFechaAutorizacion = retFechaAutorizacion;
    }

    @Column(name = "ret_identificacion_emisor", nullable = false, length = 13)
    public String getRetIdentificacionEmisor() {
        return retIdentificacionEmisor;
    }

    public void setRetIdentificacionEmisor(String retIdentificacionEmisor) {
        this.retIdentificacionEmisor = retIdentificacionEmisor;
    }

    @Column(name = "ret_razon_social_emisor", nullable = false, length = 250)
    public String getRetRazonSocialEmisor() {
        return retRazonSocialEmisor;
    }

    public void setRetRazonSocialEmisor(String retRazonSocialEmisor) {
        this.retRazonSocialEmisor = retRazonSocialEmisor;
    }
    
    

    @Column(name = "ret_establecimiento", nullable = false, length = 3)
    public String getRetEstablecimiento() {
        return this.retEstablecimiento;
    }

    public void setRetEstablecimiento(String retEstablecimiento) {
        this.retEstablecimiento = retEstablecimiento;
    }

    @Column(name = "ret_punto_emision", nullable = false, length = 3)
    public String getRetPuntoEmision() {
        return this.retPuntoEmision;
    }

    public void setRetPuntoEmision(String retPuntoEmision) {
        this.retPuntoEmision = retPuntoEmision;
    }

    @Column(name = "ret_secuencial", nullable = false)
    public int getRetSecuencial() {
        return this.retSecuencial;
    }

    public void setRetSecuencial(int retSecuencial) {
        this.retSecuencial = retSecuencial;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "ret_fecha_emision", nullable = false, length = 13)
    public Date getRetFechaEmision() {
        return this.retFechaEmision;
    }

    public void setRetFechaEmision(Date retFechaEmision) {
        this.retFechaEmision = retFechaEmision;
    }

    @Column(name = "ret_identificacion_retenido", nullable = false, length = 13)
    public String getRetIdentificacionRetenido() {
        return this.retIdentificacionRetenido;
    }

    public void setRetIdentificacionRetenido(String retIdentificacionRetenido) {
        this.retIdentificacionRetenido = retIdentificacionRetenido;
    }

    @Column(name = "ret_razon_social_retenido", nullable = false, length = 250)
    public String getRetRazonSocialRetenido() {
        return this.retRazonSocialRetenido;
    }

    public void setRetRazonSocialRetenido(String retRazonSocialRetenido) {
        this.retRazonSocialRetenido = retRazonSocialRetenido;
    }

  

    @Column(name = "ret_valor_retenido", nullable = false, precision = 17, scale = 17)
    public double getRetValorRetenido() {
        return this.retValorRetenido;
    }

    public void setRetValorRetenido(double retValorRetenido) {
        this.retValorRetenido = retValorRetenido;
    }

    
}
