package factura.entities;
// Generated 13-dic-2013 0:40:01 by Hibernate Tools 3.2.1.GA

import ec.ste.factura.DatabaseEntity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tipo generated by hbm2java
 */
@Entity
@Table(name = "tipo", schema = "public")
public class Tipo extends DatabaseEntity implements java.io.Serializable {

    private String tipCodigo;
    private String tipNombre;

    public Tipo() {
    }

    public Tipo(String tipCodigo, String tipNombre) {
        this.tipCodigo = tipCodigo;
        this.tipNombre = tipNombre;
    }

    @Id
    @Column(name = "tip_codigo", unique = true, nullable = false, length = 3)
    public String getTipCodigo() {
        return this.tipCodigo;
    }

    public void setTipCodigo(String tipCodigo) {
        this.tipCodigo = tipCodigo;
    }

    @Column(name = "tip_nombre", nullable = false, length = 50)
    public String getTipNombre() {
        return this.tipNombre;
    }

    public void setTipNombre(String tipNombre) {
        this.tipNombre = tipNombre;
    }
}
