package ec.ste.factura.entities;
// Generated 13-dic-2013 0:40:01 by Hibernate Tools 3.2.1.GA

import ec.ste.factura.DatabaseEntity;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Empresa generated by hbm2java
 */
@Entity
@Table(name = "empresa", schema = "public")
public class Empresa extends DatabaseEntity implements java.io.Serializable {

    private String empCodigo;
    private String empRazonSocial;
    private String empMail;
    private String empTelefono;
    private String empDireccion;
    private String empUrl;
    

    public Empresa() {
    }

    public Empresa(String empCodigo, String empRazonSocial, String empMail, String empTelefono, String empDireccion, String empUrl) {
        this.empCodigo = empCodigo;
        this.empRazonSocial = empRazonSocial;
        this.empMail = empMail;
        this.empTelefono = empTelefono;
        this.empDireccion = empDireccion;
        this.empUrl = empUrl;
    }

    
    @Id
    @Column(name = "emp_codigo", unique = true, nullable = false, length = 13)
    public String getEmpCodigo() {
        return this.empCodigo;
    }

    public void setEmpCodigo(String empCodigo) {
        this.empCodigo = empCodigo;
    }

    @Column(name = "emp_razon_social", nullable = false, length = 250)
    public String getEmpRazonSocial() {
        return this.empRazonSocial;
    }

    public void setEmpRazonSocial(String empRazonSocial) {
        this.empRazonSocial = empRazonSocial;
    }

    @Column(name = "emp_mail", nullable = false, length = 300)
    public String getEmpMail() {
        return this.empMail;
    }

    public void setEmpMail(String empMail) {
        this.empMail = empMail;
    }

    @Column(name = "emp_telefono", nullable = false, length = 20)
    public String getEmpTelefono() {
        return this.empTelefono;
    }

    public void setEmpTelefono(String empTelefono) {
        this.empTelefono = empTelefono;
    }

    @Column(name = "emp_direccion", nullable = false, length = 250)
    public String getEmpDireccion() {
        return this.empDireccion;
    }

    public void setEmpDireccion(String empDireccion) {
        this.empDireccion = empDireccion;
    }

    @Column(name = "emp_url", unique = true, length = 50)
    public String getEmpUrl() {
        return empUrl;
    }

    public void setEmpUrl(String empUrl) {
        this.empUrl = empUrl;
    }
    
    
}
