package ec.ste.factura.entities;
// Generated 13-dic-2013 0:40:01 by Hibernate Tools 3.2.1.GA

import ec.ste.factura.DatabaseEntity;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Factura generated by hbm2java
 */
@Entity
@Table(name = "factura", schema = "public")
public class Factura extends DatabaseEntity implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "fac_codigo", unique = true, nullable = false)
    private int facCodigo;
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "emp_codigo")
    private Empresa empresa;
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "tip_codigo")
    private Tipo tipo;
    @Column(name = "fac_num_autorizacion", nullable = false, length = 100)
    private String facNumAutorizacion;
    @Column(name = "fac_fecha_autorizacion", nullable = false, length = 50)
    private String facFechaAutorizacion;
    @Column(name = "fac_identificacion_vendedor", nullable = false, length = 13)
    private String facIdentificacionVendedor;
    @Column(name = "fac_razon_social_vendedor", nullable = false, length = 250)
    private String facRazonSocialVendedor;
    @Column(name = "fac_establecimiento", nullable = false, length = 3)
    private String facEstablecimiento;
    @Column(name = "fac_punto_emision", nullable = false, length = 3)
    private String facPuntoEmision;
    @Column(name = "fac_secuencial", nullable = false)
    private int facSecuencial;
    @Temporal(TemporalType.DATE)
    @Column(name = "fac_fecha_emision", nullable = false, length = 13)
    private Date facFechaEmision;
    @Column(name = "fac_identificacion_comprador", nullable = false, length = 13)
    private String facIdentificacionComprador;
    @Column(name = "fac_razon_social_comprador", nullable = false, length = 250)
    private String facRazonSocialComprador;
    @Column(name = "fac_total_sin_impuestos", nullable = false, precision = 17, scale = 17)
    private double facTotalSinImpuestos;
    @Column(name = "fac_total_descuento", nullable = false, precision = 17, scale = 17)
    private double facTotalDescuento;
    @Column(name = "fac_importe_total", nullable = false, precision = 17, scale = 17)
    private double facImporteTotal;

    public Factura() {
    }

    public Factura(int facCodigo, String facNumAutorizacion, String facFechaAutorizacion, String facEstablecimiento, String facPuntoEmision, int facSecuencial, Date facFechaEmision, String facIdentificacionComprador, String facRazonSocialComprador, double facTotalSinImpuestos, double facTotalDescuento, double facImporteTotal) {
        this.facCodigo = facCodigo;
        this.facNumAutorizacion = facNumAutorizacion;
        this.facFechaAutorizacion = facFechaAutorizacion;
        this.facEstablecimiento = facEstablecimiento;
        this.facPuntoEmision = facPuntoEmision;
        this.facSecuencial = facSecuencial;
        this.facFechaEmision = facFechaEmision;
        this.facIdentificacionComprador = facIdentificacionComprador;
        this.facRazonSocialComprador = facRazonSocialComprador;
        this.facTotalSinImpuestos = facTotalSinImpuestos;
        this.facTotalDescuento = facTotalDescuento;
        this.facImporteTotal = facImporteTotal;
    }

    public Factura(int facCodigo, Empresa empresa, Tipo tipo, String facNumAutorizacion, String facFechaAutorizacion, String facEstablecimiento, String facPuntoEmision, int facSecuencial, Date facFechaEmision, String facIdentificacionComprador, String facRazonSocialComprador, double facTotalSinImpuestos, double facTotalDescuento, double facImporteTotal) {
        this.facCodigo = facCodigo;
        this.empresa = empresa;
        this.tipo = tipo;
        this.facNumAutorizacion = facNumAutorizacion;
        this.facFechaAutorizacion = facFechaAutorizacion;
        this.facEstablecimiento = facEstablecimiento;
        this.facPuntoEmision = facPuntoEmision;
        this.facSecuencial = facSecuencial;
        this.facFechaEmision = facFechaEmision;
        this.facIdentificacionComprador = facIdentificacionComprador;
        this.facRazonSocialComprador = facRazonSocialComprador;
        this.facTotalSinImpuestos = facTotalSinImpuestos;
        this.facTotalDescuento = facTotalDescuento;
        this.facImporteTotal = facImporteTotal;
    }

    public int getFacCodigo() {
        return this.facCodigo;
    }

    public void setFacCodigo(int facCodigo) {
        this.facCodigo = facCodigo;
    }

    public Empresa getEmpresa() {
        return this.empresa;
    }

    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    public Tipo getTipo() {
        return this.tipo;
    }

    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }

    public String getFacNumAutorizacion() {
        return this.facNumAutorizacion;
    }

    public void setFacNumAutorizacion(String facNumAutorizacion) {
        this.facNumAutorizacion = facNumAutorizacion;
    }

    public String getFacFechaAutorizacion() {
        return this.facFechaAutorizacion;
    }

    public void setFacFechaAutorizacion(String facFechaAutorizacion) {
        this.facFechaAutorizacion = facFechaAutorizacion;
    }

    public String getFacIdentificacionVendedor() {
        return facIdentificacionVendedor;
    }

    public void setFacIdentificacionVendedor(String facIdentificacionVendedor) {
        this.facIdentificacionVendedor = facIdentificacionVendedor;
    }

    public String getFacRazonSocialVendedor() {
        return facRazonSocialVendedor;
    }

    public void setFacRazonSocialVendedor(String facRazonSocialVendedor) {
        this.facRazonSocialVendedor = facRazonSocialVendedor;
    }

    public String getFacEstablecimiento() {
        return this.facEstablecimiento;
    }

    public void setFacEstablecimiento(String facEstablecimiento) {
        this.facEstablecimiento = facEstablecimiento;
    }

    public String getFacPuntoEmision() {
        return this.facPuntoEmision;
    }

    public void setFacPuntoEmision(String facPuntoEmision) {
        this.facPuntoEmision = facPuntoEmision;
    }
    
    public String getFacSecuencial() {
        return String.format("%09d",  this.facSecuencial);
    }

    public void setFacSecuencial(int facSecuencial) {
        this.facSecuencial = facSecuencial;
    }

    public Date getFacFechaEmision() {
        return this.facFechaEmision;
    }

    public void setFacFechaEmision(Date facFechaEmision) {
        this.facFechaEmision = facFechaEmision;
    }

    public String getFacIdentificacionComprador() {
        return this.facIdentificacionComprador;
    }

    public void setFacIdentificacionComprador(String facIdentificacionComprador) {
        this.facIdentificacionComprador = facIdentificacionComprador;
    }

    public String getFacRazonSocialComprador() {
        return this.facRazonSocialComprador;
    }

    public void setFacRazonSocialComprador(String facRazonSocialComprador) {
        this.facRazonSocialComprador = facRazonSocialComprador;
    }

    public double getFacTotalSinImpuestos() {
        return this.facTotalSinImpuestos;
    }

    public void setFacTotalSinImpuestos(double facTotalSinImpuestos) {
        this.facTotalSinImpuestos = facTotalSinImpuestos;
    }

    public double getFacTotalDescuento() {
        return this.facTotalDescuento;
    }

    public void setFacTotalDescuento(double facTotalDescuento) {
        this.facTotalDescuento = facTotalDescuento;
    }

    public double getFacImporteTotal() {
        return this.facImporteTotal;
    }

    public void setFacImporteTotal(double facImporteTotal) {
        this.facImporteTotal = facImporteTotal;
    }

    @Override
    public String toString() {
        String text = facNumAutorizacion;
        if (text == null) {
            return "";
        }
        if (text.length() < 30) {
            return "";
        }
        return text.substring(0, 10) + " " + text.substring(10, 20) + " " + text.substring(20, 30) + " " + text.substring(30, text.length());
    }

}
