package ec.ste.factura.entities;
// Generated 13-dic-2013 0:40:01 by Hibernate Tools 3.2.1.GA

import ec.ste.factura.DatabaseEntity;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GuiaRemision generated by hbm2java
 */
@Entity
@Table(name = "guia_remision", schema = "public")
public class GuiaRemision extends DatabaseEntity implements java.io.Serializable {

    private int greCodigo;
    private Empresa empresa;
    private Tipo tipo;
    private String greNumAutorizacion;
    private String greFechaAutorizacion;
    private String greEstablecimiento;
    private String grePuntoEmision;
    private int greSecuencial;
    private Date greFechaEmision;
    private String greIdentificacionVendedor;
    private String greRazonSocialVendedor;
    private String greIdentificacionComprador;
    private String greRazonSocialComprador;
    private String greNumDocModificado;
    private double greTotalSinImpuestos;
    private double greValorModificacion;

    public GuiaRemision() {
    }

    

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "gre_codigo", unique = true, nullable = false)
    public int getGreCodigo() {
        return this.greCodigo;
    }

    public void setGreCodigo(int greCodigo) {
        this.greCodigo = greCodigo;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "emp_codigo")
    public Empresa getEmpresa() {
        return this.empresa;
    }

    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "tip_codigo")
    public Tipo getTipo() {
        return this.tipo;
    }

    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }

    @Column(name = "gre_num_autorizacion", nullable = false, length = 100)
    public String getGreNumAutorizacion() {
        return this.greNumAutorizacion;
    }

    public void setGreNumAutorizacion(String greNumAutorizacion) {
        this.greNumAutorizacion = greNumAutorizacion;
    }

    @Column(name = "gre_fecha_autorizacion", nullable = false, length = 50)
    public String getGreFechaAutorizacion() {
        return this.greFechaAutorizacion;
    }

    public void setGreFechaAutorizacion(String greFechaAutorizacion) {
        this.greFechaAutorizacion = greFechaAutorizacion;
    }

    @Column(name = "gre_establecimiento", nullable = false, length = 3)
    public String getGreEstablecimiento() {
        return this.greEstablecimiento;
    }

    public void setGreEstablecimiento(String greEstablecimiento) {
        this.greEstablecimiento = greEstablecimiento;
    }

    @Column(name = "gre_punto_emision", nullable = false, length = 3)
    public String getGrePuntoEmision() {
        return this.grePuntoEmision;
    }

    public void setGrePuntoEmision(String grePuntoEmision) {
        this.grePuntoEmision = grePuntoEmision;
    }

    @Column(name = "gre_secuencial", nullable = false)
    public int getGreSecuencial() {
        return this.greSecuencial;
    }

    public void setGreSecuencial(int greSecuencial) {
        this.greSecuencial = greSecuencial;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "gre_fecha_emision", nullable = false, length = 13)
    public Date getGreFechaEmision() {
        return this.greFechaEmision;
    }

    public void setGreFechaEmision(Date greFechaEmision) {
        this.greFechaEmision = greFechaEmision;
    }

    @Column(name = "gre_identificacion_vendedor", nullable = false, length = 13)
    public String getGreIdentificacionVendedor() {
        return greIdentificacionVendedor;
    }

    public void setGreIdentificacionVendedor(String greIndetificacionVendedor) {
        this.greIdentificacionVendedor = greIndetificacionVendedor;
    }

    @Column(name = "gre_razon_social_vendedor", nullable = false, length = 250)
    public String getGreRazonSocialVendedor() {
        return greRazonSocialVendedor;
    }

    public void setGreRazonSocialVendedor(String greRazonSocialVendedor) {
        this.greRazonSocialVendedor = greRazonSocialVendedor;
    }
    
    

    @Column(name = "gre_identificacion_comprador", nullable = false, length = 13)
    public String getGreIndetificacionComprador() {
        return this.greIdentificacionComprador;
    }

    public void setGreIndetificacionComprador(String greIndetificacionComprador) {
        this.greIdentificacionComprador = greIndetificacionComprador;
    }

    @Column(name = "gre_razon_social_comprador", nullable = false, length = 250)
    public String getGreRazonSocialComprador() {
        return this.greRazonSocialComprador;
    }

    public void setGreRazonSocialComprador(String greRazonSocialComprador) {
        this.greRazonSocialComprador = greRazonSocialComprador;
    }

    @Column(name = "gre_num_doc_modificado", nullable = false, length = 25)
    public String getGreNumDocModificado() {
        return this.greNumDocModificado;
    }

    public void setGreNumDocModificado(String greNumDocModificado) {
        this.greNumDocModificado = greNumDocModificado;
    }

    @Column(name = "gre_total_sin_impuestos", nullable = false, precision = 17, scale = 17)
    public double getGreTotalSinImpuestos() {
        return this.greTotalSinImpuestos;
    }

    public void setGreTotalSinImpuestos(double greTotalSinImpuestos) {
        this.greTotalSinImpuestos = greTotalSinImpuestos;
    }

    @Column(name = "gre_valor_modificacion", nullable = false, precision = 17, scale = 17)
    public double getGreValorModificacion() {
        return this.greValorModificacion;
    }

    public void setGreValorModificacion(double greValorModificacion) {
        this.greValorModificacion = greValorModificacion;
    }
}
