package ec.ste.factura.entities;
// Generated 13-dic-2013 0:40:01 by Hibernate Tools 3.2.1.GA

import ec.ste.factura.DatabaseEntity;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NotaCredito generated by hbm2java
 */
@Entity
@Table(name = "nota_credito", schema = "public")
public class NotaCredito extends DatabaseEntity implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ncr_codigo", unique = true, nullable = false)
    private int ncrCodigo;
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "emp_codigo")
    private Empresa empresa;
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "tip_codigo")
    private Tipo tipo;
    @Column(name = "ncr_num_autorizacion", nullable = false, length = 100)
    private String ncrNumAutorizacion;
    @Column(name = "ncr_fecha_autorizacion", nullable = false, length = 50)
    private String ncrFechaAutorizacion;
    @Column(name = "ncr_establecimiento", nullable = false, length = 3)
    private String ncrEstablecimiento;
    @Column(name = "ncr_punto_emision", nullable = false, length = 3)
    private String ncrPuntoEmision;
    @Column(name = "ncr_secuencial", nullable = false)
    private int ncrSecuencial;
    @Temporal(TemporalType.DATE)
    @Column(name = "ncr_fecha_emision", nullable = false, length = 13)
    private Date ncrFechaEmision;
    @Column(name = "ncr_identificacion_vendedor", nullable = false, length = 13)
    private String ncrIdentificacionVendedor;
    @Column(name = "ncr_razon_social_vendedor", nullable = false, length = 250)
    private String ncrRazonSocialVendedor;
    @Column(name = "ncr_identificacion_comprador", nullable = false, length = 13)
    private String ncrIdentificacionComprador;
    @Column(name = "ncr_razon_social_comprador", nullable = false, length = 250)
    private String ncrRazonSocialComprador;
    @Column(name = "ncr_num_doc_modificado", nullable = false, length = 25)
    private String ncrNumDocModificado;
    @Column(name = "ncr_total_sin_impuestos", nullable = false, precision = 17, scale = 17)
    private double ncrTotalSinImpuestos;
    @Column(name = "ncr_valor_modificacion", nullable = false, precision = 17, scale = 17)
    private double ncrValorModificacion;

    public NotaCredito() {
    }

    public int getNcrCodigo() {
        return this.ncrCodigo;
    }

    public void setNcrCodigo(int ncrCodigo) {
        this.ncrCodigo = ncrCodigo;
    }

    public Empresa getEmpresa() {
        return this.empresa;
    }

    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    public Tipo getTipo() {
        return this.tipo;
    }

    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }

    public String getNcrNumAutorizacion() {
        return this.ncrNumAutorizacion;
    }

    public void setNcrNumAutorizacion(String ncrNumAutorizacion) {
        this.ncrNumAutorizacion = ncrNumAutorizacion;
    }

    public String getNcrFechaAutorizacion() {
        return this.ncrFechaAutorizacion;
    }

    public void setNcrFechaAutorizacion(String ncrFechaAutorizacion) {
        this.ncrFechaAutorizacion = ncrFechaAutorizacion;
    }

    public String getNcrEstablecimiento() {
        return this.ncrEstablecimiento;
    }

    public void setNcrEstablecimiento(String ncrEstablecimiento) {
        this.ncrEstablecimiento = ncrEstablecimiento;
    }

    public String getNcrPuntoEmision() {
        return this.ncrPuntoEmision;
    }

    public void setNcrPuntoEmision(String ncrPuntoEmision) {
        this.ncrPuntoEmision = ncrPuntoEmision;
    }

    public String getNcrSecuencial() {
        return String.format("%09d",  this.ncrSecuencial);
    }

    public void setNcrSecuencial(int ncrSecuencial) {
        this.ncrSecuencial = ncrSecuencial;
    }

    public Date getNcrFechaEmision() {
        return this.ncrFechaEmision;
    }

    public void setNcrFechaEmision(Date ncrFechaEmision) {
        this.ncrFechaEmision = ncrFechaEmision;
    }

    public String getNcrIdentificacionVendedor() {
        return ncrIdentificacionVendedor;
    }

    public void setNcrIdentificacionVendedor(String ncrIdentificacionVendedor) {
        this.ncrIdentificacionVendedor = ncrIdentificacionVendedor;
    }

    public String getNcrRazonSocialVendedor() {
        return ncrRazonSocialVendedor;
    }

    public void setNcrRazonSocialVendedor(String ncrRazonSocialVendedor) {
        this.ncrRazonSocialVendedor = ncrRazonSocialVendedor;
    }

    public String getNcrIdentificacionComprador() {
        return this.ncrIdentificacionComprador;
    }

    public void setNcrIdentificacionComprador(String ncrIdentificacionComprador) {
        this.ncrIdentificacionComprador = ncrIdentificacionComprador;
    }

    public String getNcrRazonSocialComprador() {
        return this.ncrRazonSocialComprador;
    }

    public void setNcrRazonSocialComprador(String ncrRazonSocialComprador) {
        this.ncrRazonSocialComprador = ncrRazonSocialComprador;
    }

    public String getNcrNumDocModificado() {
        return this.ncrNumDocModificado;
    }

    public void setNcrNumDocModificado(String ncrNumDocModificado) {
        this.ncrNumDocModificado = ncrNumDocModificado;
    }

    public double getNcrTotalSinImpuestos() {
        return this.ncrTotalSinImpuestos;
    }

    public void setNcrTotalSinImpuestos(double ncrTotalSinImpuestos) {
        this.ncrTotalSinImpuestos = ncrTotalSinImpuestos;
    }

    public double getNcrValorModificacion() {
        return this.ncrValorModificacion;
    }

    public void setNcrValorModificacion(double ncrValorModificacion) {
        this.ncrValorModificacion = ncrValorModificacion;
    }
}
