package ec.ste.factura.entities;
// Generated 13-dic-2013 0:40:01 by Hibernate Tools 3.2.1.GA

import ec.ste.factura.DatabaseEntity;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name = "perfil", schema = "public")
public class Perfil extends DatabaseEntity implements java.io.Serializable {

    private String prfCodigo;
    private String prfNombre;

    public Perfil() {
    }

    public Perfil(String prfCodigo, String prfNombre) {
        this.prfCodigo = prfCodigo;
        this.prfNombre = prfNombre;
    }

    @Id
    @Column(name = "prf_codigo", unique = true, nullable = false, length = 3)
    public String getPrfCodigo() {
        return this.prfCodigo;
    }

    public void setPrfCodigo(String prfCodigo) {
        this.prfCodigo = prfCodigo;
    }

    @Column(name = "prf_nombre", nullable = false, length = 50)
    public String getPrfNombre() {
        return this.prfNombre;
    }

    public void setPrfNombre(String prfNombre) {
        this.prfNombre = prfNombre;
    }
}
