
package ec.ste.docusend.wsc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSLoader", targetNamespace = "http://load.ws.factura.ste.ec/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSLoader {


    /**
     * 
     * @param nick
     * @param ruc
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://load.ws.factura.ste.ec/", className = "ec.ste.docusend.wsc.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://load.ws.factura.ste.ec/", className = "ec.ste.docusend.wsc.LoginResponse")
    @Action(input = "http://load.ws.factura.ste.ec/WSLoader/loginRequest", output = "http://load.ws.factura.ste.ec/WSLoader/loginResponse")
    public String login(
            @WebParam(name = "ruc", targetNamespace = "")
                    String ruc,
            @WebParam(name = "nick", targetNamespace = "")
                    String nick,
            @WebParam(name = "password", targetNamespace = "")
                    String password);

    /**
     * 
     * @param rucEmpresa
     * @param registerType
     * @param nick
     * @param xmlData
     * @param fileName
     * @param clave
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "documentLoader", targetNamespace = "http://load.ws.factura.ste.ec/", className = "ec.ste.docusend.wsc.DocumentLoader")
    @ResponseWrapper(localName = "documentLoaderResponse", targetNamespace = "http://load.ws.factura.ste.ec/", className = "ec.ste.docusend.wsc.DocumentLoaderResponse")
    @Action(input = "http://load.ws.factura.ste.ec/WSLoader/documentLoaderRequest", output = "http://load.ws.factura.ste.ec/WSLoader/documentLoaderResponse")
    public String documentLoader(
            @WebParam(name = "rucEmpresa", targetNamespace = "")
                    String rucEmpresa,
            @WebParam(name = "nick", targetNamespace = "")
                    String nick,
            @WebParam(name = "clave", targetNamespace = "")
                    String clave,
            @WebParam(name = "fileName", targetNamespace = "")
                    String fileName,
            @WebParam(name = "registerType", targetNamespace = "")
                    int registerType,
            @WebParam(name = "xmlData", targetNamespace = "")
                    byte[] xmlData);

}
